apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
  - name: ax
    image: alianinho/web:1
    command: ['sh','-c', 'while true; do sleep 3600; done']
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "500m"
        memory: "256Mi"

