apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: nginx
    image: nginx:1.19.1
    ports:
    - containerPort: 80
    volumeMounts:
    - name: config-volume
      mountPath: /etc/nginx
    - name: htpasswd-volume
      mountPath: /etc/nginx/conf
  volumes:
  - name: config-volume
    configMap:
      name: my-configmap
  - name: htpasswd-volume
    secret:
      secretName: nginx-htpasswd #make it beforehead  $htpasswd -c .htpasswd alianinho and $kubectl create secret generic nginx-htpasswd --from-file .htpasswd

