apiVersion : apps/v1
kind: Deployment
metadata:
  name: web-manifest-replica2 #name of the deployment
  labels:
    app: manifest-app2
spec:
  #replicas: 3 was changed to autoscaling
  selector:
    matchLabels:
      project: web2
  template:
    metadata:
      labels:
        project: web2    #pods labels
    spec:
      containers:
        - name: web2
          image: alianinho/aliaweb:v1
          ports:
           - containerPort: 80

---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: autoscaling
spec:
  scaleTargetRef:
    apiVersion: apps/v2beta1v1
    kind: Deployment
    name: web-manifest-replica2 #name of the deployment to scale
  minReplicas: 2
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 70
  - type: Resource
    resource:
      name: memory
      targetAverageUtilization: 80

---
apiVersion: v1
kind: Service
metadata:
  name: prod-service-autoscale
  labels:    #mandatory
    env: prod
    owner: alianinho
spec:
  selector:
    project: web2 #project pods with this label will be attached with LB
  ports:
    - name: app-listener
      port: 80       #port on LB
      targetPort: 80 #port on pod
  type: LoadBalancer