apiVersion: v1
kind: Pod
metadata:
  name: liveness-pod
spec:
  containers:
    - name: busybox
      image: busybox
      command: ['sh','-c','while true; do sleep 3600; done']
      livenessProbe:
        exec:  #RUN COMMAND INSIDE A CONTAINER IF SUCCEED
          command: ["echo", "Hello, world"]
        initialDelaySeconds: 5 #delay before command will be executed
        periodSeconds: 5 #how frequently command will be ran (every 5 seconds) (frequently of the health-check)
