apiVersion: v1
kind: Pod
metadata:
  name: readliness-liveness-pod-http
spec:
  containers:
    - name: nginx
      image: nginx:1.19.1
      livenessProbe:
        httpGet:
          path: /
          port: 80
        initialDelaySeconds: 5 #delay before container start
        periodSeconds: 5 #frequently of the health-check to restart the container
      readinessProbe:
        httpGet:
          path: /
          port: 80
        initialDelaySeconds: 5 #delay before container start
        periodSeconds: 5 #frequently of the health-check to prevent traffic to the container